name: pavura
description: "All-in-one transportation and ride-hailing app for Malaysia. Track buses, plan routes, and book rides seamlessly."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.4.3
  
  # Networking
  http: ^1.6.0
  
  # State Management
  provider: ^6.1.5+1
  
  # UI & Design
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  google_maps_flutter: ^2.5.0
  
  # Location & Geocoding
  geolocator: ^9.0.2
  geocoding: ^2.1.1
  permission_handler: ^11.3.1
  
  # Utilities
  intl: ^0.19.0
  archive: ^3.4.0
  grpc: ^3.2.4
  gtfs_realtime_bindings: ^1.1.0
  shared_preferences: ^2.3.5
  flutter_map_cancellable_tile_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/train_logos/
    - assets/gtfs_rapid_rail_kl/
