// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxMnFSDwA4vYSxAXLHvqRor3FYx2Mki_E',
    appId: '1:912472454203:web:908170041c2ac31904d81e',
    messagingSenderId: '912472454203',
    projectId: 'pavura',
    authDomain: 'pavura.firebaseapp.com',
    storageBucket: 'pavura.firebasestorage.app',
    measurementId: 'G-23TVCC2SQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiJNr_q6PebXD1rKFU6h0deUm1V-N-lq0',
    appId: '1:912472454203:android:cc92120e707948ff04d81e',
    messagingSenderId: '912472454203',
    projectId: 'pavura',
    storageBucket: 'pavura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG6kS1N6NgzIhWWbT7-Pd-NNyjWfXobR8',
    appId: '1:912472454203:ios:4c65895ae937525904d81e',
    messagingSenderId: '912472454203',
    projectId: 'pavura',
    storageBucket: 'pavura.firebasestorage.app',
    iosBundleId: 'com.example.passengerTransportationTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG6kS1N6NgzIhWWbT7-Pd-NNyjWfXobR8',
    appId: '1:912472454203:ios:4c65895ae937525904d81e',
    messagingSenderId: '912472454203',
    projectId: 'pavura',
    storageBucket: 'pavura.firebasestorage.app',
    iosBundleId: 'com.example.passengerTransportationTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxMnFSDwA4vYSxAXLHvqRor3FYx2Mki_E',
    appId: '1:912472454203:web:09741277b2b84c4d04d81e',
    messagingSenderId: '912472454203',
    projectId: 'pavura',
    authDomain: 'pavura.firebaseapp.com',
    storageBucket: 'pavura.firebasestorage.app',
    measurementId: 'G-2MEJ3ZZCFF',
  );
}
